### ISSUE TITLE
Heatmap broke when upgrading 0.2 -> 0.3 (still broken on 0.5)

### ISSUE THREAD

**Issue by IanQS** [Richardsl/heatmap-calendar-obsidian#23] opened 2022-07-01 21:11 UTC
Hi there! It seems like one of the updates in the `main.js` caused my heatmap to stop displaying.

Here it is working with `main.js` from `0.2`:
![2022-07-01-140128_1920x1080_scrot](https://user-images.githubusercontent.com/6968573/176967989-0e213ebb-87d0-4cbe-9343-8a70c91097d7.png)

and here is when I update `main.js` to what is on `0.3`

![2022-07-01-140257_1920x1080_scrot](https://user-images.githubusercontent.com/6968573/176967756-335baa93-0561-4cca-8847-9557a7f88860.png)

I'd love to get your insight into what might be causing this. The issue persists on light mode theme as well so presumably it's not the styling

**Comment by PaperOrb** [comment] 2022-07-02 19:10
Hi, I can confirm I'm having the same issue. Same issue on 0.5 as well. It looks like my metadata is no longer being displayed in the heatmap:
![heatmap](https://user-images.githubusercontent.com/48017994/177013454-3afa81f1-ee40-4c32-9b9c-de86e5964d64.png)

**Comment by Richardsl** [comment] 2022-07-04 10:40
Hi, sorry to hear that.
Can you show me your code for the calendars? 
I can maybe try to replicate the issue, as it seems to work with me.

also, if you try to print out the metadata by adding a dv.paragraph like the example below, does it display any data?

```

dv.span("**🍺 Alcohol Consumption 🍺**")

const calendarData = {
    entries: [],
}
for(let page of dv.pages('"daily notes"').where(p=>p.alcohol).sort(p=>p.file.name)){
	dv.paragraph(page.file.name + " Alcohol units: " + page.alcohol) 
        calendarData.entries.push({
            date: page.file.name,
            intensity: page.alcohol,
    })  
}

renderHeatmapCalendar(this.container, calendarData)

```
expected result:
![bilde](https://user-images.githubusercontent.com/7509515/177138505-965604ce-833a-4108-89ee-d47e6c49fb47.png)

**Comment by ninjannette** [comment] 2022-07-06 08:16
Hi, I'm having the same issue now. Just downloaded this codeblock and opened as a new vault with Dataview, style snippets, Daily Notes and calendar enabled just in case. But its appearing as blank calendars like this despite the presence of the sample vault periodic notes-
![Screen Shot 2022-07-06 at 4 15 43 PM](https://user-images.githubusercontent.com/106827768/177503502-5bd97661-1e13-4d66-a29f-4852bfb95a94.png)

**Comment by Richardsl** [comment] 2022-07-07 13:07
what operating system are you using?
what timezone are you in?

**Comment by IanQS** [comment] 2022-07-07 13:32
I'm using arch linux and I'm on GMT-7 (Los Angeles time)

**Comment by Richardsl** [comment] 2022-07-07 15:26
is dataviewjs itself generally working? independently from heatmap?

**Comment by lovwyr** [comment] 2022-07-07 20:58
I can confirm the behavior on an System with German Language settings. But from what i can say its only happening if intensity is set on the Entrys.

**Comment by Richardsl** [comment] 2022-07-07 21:54
what version of obsidian are you guys running? 
I can't seem to replicate the error. I've tried reinstalling on an ubuntu distro on a VM aswell, but everything seems to be working fine

**Comment by lovwyr** [comment] 2022-07-07 21:59
0.15.4 on my side,

a little bit digging around later :), after the calendarData.entries.filter has run the calEntries Array is completly empty for whatever Reasons...

**Comment by Richardsl** [comment] 2022-07-07 23:13
I made a few changes - hopefully it will fix the issue, but im not sure since i can't replicate the bug.
Please update to 0.5.1 and keep me posted :)

**Comment by IanQS** [comment] 2022-07-08 03:06
I can now see the entries! I can't hover, but I can see the entries. 

![2022-07-07-200009_1920x1080_scrot](https://user-images.githubusercontent.com/6968573/177908922-eb08dd8f-067c-400f-8595-199bafc61a00.png)

My code looks like 

```
const calendarData = {
    year: 2022,
	colors: {
		red: ["#ff9e82","#ff7b55","#ff4d1a","#e73400","#bd2a00"]
    },
    entries: []
}

for(let page of dv.pages('"journals"').where(p=>p.exercise).sort(p=>p.file.name)){
	let color = "red"
	if (page.exercise < 10){
		color = "red"
	} 
    calendarData.entries.push({
        date: page.file.name,
        color: color,
        content: await dv.span(`[](${page.file.name})`)
    })   
}

	
renderHeatmapCalendar(this.container, calendarData)
```

My daily note format is `MMM D, YYYY`. Does any of you know how to change hte default parsing format by any chance? JS isn't my forte and I'm confused as to how to parse it. It's not clear to me how it works at all and why it breaks on this seemingly simple change

**Comment by Richardsl** [comment] 2022-07-08 12:58
Great hopefully this fixed it for everyone :) @lovwyr @ninjannette @PaperOrb ??

The plugin really doesn't support any other format than YYYY-MM-DD, but if it works for you its great.  
Preview on hover needs to be enabled in obsidian settings, and you might need to hold down **ctrl** whilst hovering if its not enabled.

you can see how to format the date here: https://github.com/Richardsl/heatmap-calendar-obsidian/discussions/2

**Comment by lovwyr** [comment] 2022-07-08 20:24
I can confirm that it is fixed with the new version. 
I had found another small problem during testing: passing the year as a string to the constructor also causes the rendering to fail but an quick dv.parse() can fix this 😄 

ps) newer dataview versions expose the luxon api, so a .toISODate() should normally be sufficient for the date of the entrys

**Comment by IanQS** [comment] 2022-07-09 13:49
@lovwyr is your "hover" working? Can you tell me what settings you're using? Mine isn't working even when I hold the CTRL button :( is your date format the same as what @Richardsl mentioned?

**Comment by lovwyr** [comment] 2022-07-09 18:42
@IanQS yes its "working", i normaly dont use it in my usecase.

the page.Published source formt was already ISO 8601
Published: "2022-03-04"

working
`content: await dv.span("[["+page.file.name+"]]"),`

not reliable working (disrupts rendering in some cases)
`content: await dv.span(`[🔗](${page.file.name})`),`


---

````dataviewjs
dv.span("**intensity On**")

const calendarData = {
    entries: [],
}

for(let page of dv.pages('"storys"').where(p=>p.Title)){
    console.log({page});
    var heatdate = page.Published.toISODate();
    calendarData.entries.push({
        date: heatdate,
        intensity: page.moneySpent, 
        content: await dv.span("[["+page.file.name+"]]"),         
    })  
    console.log({calendarData});
}

renderHeatmapCalendar(this.container, calendarData)

````

**Comment by Jinnayah** [comment] 2022-07-13 00:27
I'm still having this problem on some, but not all, of my heatmaps.  It seems to be breaking if the intensity values don't vary except for on and off.  Heatmap version 0.5.1, Obsidian 0.15.6

Here's an example where I was able to take a functioning map, and break it by changing the intensity to a set number.   
![Heatmap_test_example1](https://user-images.githubusercontent.com/100481248/178622480-81ea27d4-ed08-4376-8606-af3a1df7487f.png)
![Heatmap_test_example2](https://user-images.githubusercontent.com/100481248/178622499-6bcafa11-11c6-4ec7-809e-4dcc157a0c61.png)
 
This code failed when all of my 'spinning' entries were 0 or 1, but worked when I changed one entry to '2':
![Heatmap_test_example3](https://user-images.githubusercontent.com/100481248/178622872-19c7c019-aac2-47d5-9aa5-e99fe704bcaf.png)
![Heatmap_test_example4](https://user-images.githubusercontent.com/100481248/178623036-47ae4fed-d558-4f9a-8bfe-d45d6b8965d6.png)

**Comment by IanQS** [comment] 2022-07-13 15:36
@Jinnayah can you post the code in text as opposed to images? Makes it easier to copy paste

**Comment by Richardsl** [comment] 2022-07-13 22:12
released a new version, should be ok now.

**Comment by Jinnayah** [comment] 2022-07-14 01:13
That took care of it. :)

**Closed** 2022-07-14 21:04 UTC
