### ISSUE TITLE
FEATURE REQUEST: gray out future dates

### ISSUE THREAD

**Issue by PaperOrb** [Richardsl/heatmap-calendar-obsidian#16] opened 2022-05-31 01:42 UTC
It'd be helpful to see at a glance what day it is today by graying out all squares for dates that are in the future. Here's an example from the anki heatmap plugin.

![29401752-bf29d61a-8332-11e7-995d-73cb0b2c8caa](https://user-images.githubusercontent.com/48017994/171076297-66180ad7-b8dd-4ac5-8a46-0c90f1bc6a94.png)

**Comment by asphaltbuffet** [comment] 2022-06-21 14:59
would this be a duplicate of #17 and/or #6?

**Comment by Richardsl** [comment] 2022-06-29 22:36
Border around current day is available by default as of current release.

**Closed by Richardsl** 2022-06-29 22:36 UTC
